# Build container and push to GitHub Packages on Release
name: Docker build and push

using: "composite"
steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Extract metadata for Docker
    id: meta
    uses: docker/metadata-action@v3
    with:
      images: ${{ env.IMAGE_NAME }}

  - name: Log in to the GitHub Container registry
    if: github.event_name == "release"
    uses: docker/login-action@v1
    with:
      registry: ${{ env.REGISTRY }}
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}

  - name: Build and push Docker image
    uses: docker/build-push-action@v3
    with:
      context: .
      load: True
      push: ${{ github.event_name == "release" }}
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

  - name: Test the Docker image
    run: docker run comet* comet -p
