# Builds Comet on Linux, MacOS, and Windows
name: Build, test, and reslease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: TalusBio/comet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build Comet
      run: ./build.sh

    - name: Test the Comet executable
      run: ./comet -p

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Log in to the GitHub Container registry
      if: ${{ github.event_name == 'release' }}
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name == 'release' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Test the Docker image
      if: ${{ github.event_name != 'release' }}
      run: docker run ${REGISTRY}/talusbio/comet:main comet -p

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: ${{ github.event_name == 'release' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./comet
        asset_name: Ubuntu
        overwrite: true
