# Builds Comet on Linux, MacOS, and Windows
name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build comet
      run: ./build.sh

    - name: Test comet
      run: ./comet.exe -P

    - name: Build container
      run: |
        docker build .
