# Builds Comet on Linux, MacOS, and Windows
name: Build, test, and reslease

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: TalusBio/comet

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set version
      run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

    - name: Build Comet
      run: ./build.sh

    - name: Test the Comet executable
      run: ./comet.exe -p

    - name: Build the Docker container
      if: ${{ jobs.build.runs-on == "ubuntu-latest" }}
      using: build-docker
